"""Assemble the reviewed Markdown into navigable EPUB and print-ready HTML.

Run from any directory with: python3 scripts/build_release.py
The generated files live under dist/v2.3 and do not replace the v2.2 sources.
"""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import zipfile
from pathlib import Path
from urllib.parse import unquote


ROOT = Path(__file__).resolve().parents[1]
BOOK = ROOT / "book"
OUT = ROOT / "dist" / "v2.3"
AUTHOR = "Stallen"
FRONT = ("title", "dedication", "reader-note", "contents", "preface", "how-to-use")
BACK = ("videos", "glossary", "copyright")
REFERENCE_NAMES = (
    "git-github", "web-deployment", "backend-database", "linux-server",
    "docker", "mobile-release", "wechat-miniprogram",
    "testing-monitoring-incidents",
)
LINK = re.compile(r"(?<!!)\[([^\]]+)\]\(([^)]+)\)")
IMAGE = re.compile(r"!\[([^\]]*)\]\(([^)]+)\)")


def title_anchor(source: Path, text: str, label: str, anchor: str) -> str:
    pattern = re.compile(r"(?m)^# (.+)$")
    match = pattern.search(text)
    if not match:
        raise ValueError(f"missing level-one heading: {source}")
    return text[: match.start()] + f"# {label} {{#{anchor}}}" + text[match.end() :]


def material(source: Path, anchor: str, label: str, anchors: dict[Path, str]) -> str:
    content = title_anchor(source, source.read_text(encoding="utf-8"), label, anchor)

    def fix_image(match: re.Match[str]) -> str:
        target = unquote(match.group(2))
        if target.startswith(("http://", "https://", "data:")):
            return match.group(0)
        resolved = (source.parent / target).resolve()
        if not resolved.is_file():
            raise ValueError(f"missing image in {source}: {target}")
        return f"![{match.group(1)}]({resolved})"

    content = IMAGE.sub(fix_image, content)

    def fix_link(match: re.Match[str]) -> str:
        target = unquote(match.group(2))
        if target.startswith(("http://", "https://", "mailto:", "#")):
            return match.group(0)
        path_part, _, fragment = target.partition("#")
        resolved = (source.parent / path_part).resolve()
        if resolved.suffix != ".md":
            return match.group(0)
        if resolved not in anchors:
            raise ValueError(f"internal link lacks a book target in {source}: {target}")
        # Heading fragments generated by the old EPUB may not survive a new
        # Pandoc merge. Link to the stable chapter or appendix entrance.
        return f"[{match.group(1)}](#{anchors[resolved]})"

    content = LINK.sub(fix_link, content).strip()
    if anchor.startswith("vol-"):
        content = re.sub(r"^第\s*\d+\s*卷\s*\n", "", content)
    return content + "\n"


def assemble() -> tuple[list[Path], list[list[Path]], dict[Path, str]]:
    manifest = json.loads((BOOK / "manifest.json").read_text(encoding="utf-8"))
    chapters = manifest["chapters"]
    if [item["id"] for item in chapters] != list(range(1, 105)):
        raise ValueError("manifest must contain exactly chapters 1–104 in order")
    front = [BOOK / "frontmatter" / f"{name}.md" for name in FRONT]
    back = [BOOK / "frontmatter" / f"{name}.md" for name in BACK]
    references = [ROOT / "references" / f"{name}.md" for name in REFERENCE_NAMES]
    volumes: list[list[Path]] = []
    anchors: dict[Path, str] = {}
    for name, path in zip(FRONT, front):
        anchors[path.resolve()] = name
    for name, path in zip(BACK, back):
        anchors[path.resolve()] = name
    for name, path in zip(REFERENCE_NAMES, references):
        anchors[path.resolve()] = f"ref-{name}"
    for volume in range(1, 11):
        paths = [BOOK / "frontmatter" / f"part{volume:02d}.md"]
        anchors[paths[0].resolve()] = f"vol-{volume:02d}"
        for item in chapters:
            if item["volume"] == volume:
                path = BOOK / item["source"]
                paths.append(path)
                anchors[path.resolve()] = f"ch-{item['id']:03d}"
        volumes.append(paths)
    all_paths = front + [p for volume in volumes for p in volume] + back + references
    for path in all_paths:
        if not path.is_file():
            raise ValueError(f"missing book source: {path}")
    return all_paths, volumes, anchors


def book_contents() -> str:
    manifest = json.loads((BOOK / "manifest.json").read_text(encoding="utf-8"))
    lines = ['::: {.book-toc}', '# 目录 {#contents}', '', '全书按十卷组织。点击章名可以直接进入正文。', '']
    for volume in range(1, 11):
        volume_path = BOOK / "frontmatter" / f"part{volume:02d}.md"
        title = re.search(r"(?m)^# (.+)$", volume_path.read_text(encoding="utf-8")).group(1)
        lines.append(f'## [第 {volume} 卷　{title}](#vol-{volume:02d})')
        for item in manifest["chapters"]:
            if item["volume"] == volume:
                chapter = BOOK / item["source"]
                label = re.search(r"(?m)^# (.+)$", chapter.read_text(encoding="utf-8")).group(1)
                lines.append(f'- [第 {item["id"]:03d} 章　{label}](#ch-{item["id"]:03d})')
        lines.append('')
    lines.append(':::')
    return "\n".join(lines)


def write_markdown(paths: list[Path], anchors: dict[Path, str], target: Path) -> None:
    parts: list[str] = []
    for source in paths:
        if source.name == "cover.md":
            cover = (BOOK / "assets" / "cover.png").resolve()
            parts.append(f'<div id="pdf-cover"><img src="{cover}" alt="《AI 写代码之后》封面"></div>')
            continue
        if source.name == "contents.md":
            parts.append(book_contents())
            continue
        anchor = anchors[source.resolve()]
        text = source.read_text(encoding="utf-8")
        heading = re.search(r"(?m)^# (.+)$", text)
        if not heading:
            raise ValueError(f"missing heading: {source}")
        label = heading.group(1)
        if anchor.startswith("ch-"):
            number = int(anchor[3:])
            label = f"第 {number:03d} 章　{label}"
        elif anchor.startswith("vol-"):
            number = int(anchor[4:])
            label = f"第 {number} 卷　{label}"
        parts.append(material(source, anchor, label, anchors))
    target.write_text("\n\n".join(parts), encoding="utf-8")


def pandoc(input_file: Path, output: Path, *, fmt: str, toc: bool = False) -> None:
    stylesheet = "v2.3-epub.css" if fmt == "epub" else "v2.3.css"
    cmd = [
        "pandoc", str(input_file), "-f", "markdown-implicit_figures",
        "--standalone", "--metadata", "lang=zh-CN",
        "--metadata", "title=AI 写代码之后", "--metadata", f"author={AUTHOR}", "--css",
        str(BOOK / "assets" / "styles" / stylesheet),
    ]
    if toc:
        cmd += ["--toc", "--toc-depth=1"]
    if fmt == "epub":
        cmd += [
            "-t", "epub3", "--epub-title-page=false",
            "--epub-cover-image", str(BOOK / "assets" / "cover.png"),
        ]
    elif fmt == "html":
        cmd += ["-t", "html5", "--embed-resources"]
    else:
        raise ValueError(fmt)
    cmd += ["-o", str(output)]
    subprocess.run(cmd, cwd=ROOT, check=True)


def remove_navigation_from_reading_order(epub: Path) -> None:
    """Keep the EPUB navigation panel without paging through it as body text."""
    replacement = epub.with_suffix(".tmp.epub")
    try:
        with zipfile.ZipFile(epub) as source, zipfile.ZipFile(replacement, "w") as target:
            for entry in source.infolist():
                content = source.read(entry.filename)
                if entry.filename == "EPUB/content.opf":
                    old = b'<itemref idref="nav" />'
                    if content.count(old) != 1:
                        raise ValueError("expected one EPUB navigation spine item")
                    content = content.replace(old, b'<itemref idref="nav" linear="no" />')
                target.writestr(entry, content)
        replacement.replace(epub)
    finally:
        replacement.unlink(missing_ok=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epub", action="store_true", help="also create the final EPUB")
    args = parser.parse_args()
    OUT.mkdir(parents=True, exist_ok=True)
    all_paths, volumes, anchors = assemble()
    full_md = OUT / "AI写代码之后-v2.3.0-build.md"
    write_markdown(all_paths, anchors, full_md)
    if args.epub:
        epub = OUT / "AI写代码之后-v2.3.0.epub"
        pandoc(full_md, epub, fmt="epub", toc=True)
        remove_navigation_from_reading_order(epub)
    pdf_md = OUT / "AI写代码之后-v2.3.0-print.md"
    write_markdown([BOOK / "frontmatter" / "cover.md", *all_paths], anchors, pdf_md)
    pandoc(pdf_md, OUT / "AI写代码之后-v2.3.0-print.html", fmt="html")
    preview_sections = [[BOOK / "frontmatter" / "cover.md", *all_paths[:len(FRONT)]]]
    preview_sections += volumes
    preview_sections += [all_paths[-(len(BACK) + len(REFERENCE_NAMES)):]]
    for index, paths in enumerate(preview_sections):
        source = OUT / f"volume-{index:02d}.md"
        write_markdown(paths, anchors, source)
        pandoc(source, OUT / f"volume-{index:02d}.html", fmt="html")
    print(f"assembled {len(all_paths)} sources and {len(preview_sections)} PDF sections in {OUT}")


if __name__ == "__main__":
    main()
